---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: check-required-variable-alpine-null-variable
    image: alpine:3
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
verifier:
  name: testinfra
